name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  print:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy something
        run: |
          echo "Deploying application...."

